# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Generate Solved Problem List

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  workbook:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: generate workbook
        run: |
          python3 scripts/workbook.py

      # Commits all changed files to the repository
      - name: Commit to the repo
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          # "echo" returns true so the build succeeds, even if no changed files
          git commit -m 'workbook을 업데이트 하였습니다' || echo
          git push

  markdown:
    runs-on: ubuntu-latest

    needs: workbook # workbook 먼저 해줘야함

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2

      # install packages
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install npm packages
        run: yarn install

      # generate markdown file
      - name: Generate markdown file
        run: yarn generate

      # Commits all changed files to the repository
      - name: Commit to the repo
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull origin main
          git add .
          # "echo" returns true so the build succeeds, even if no changed files
          git commit -m '해결한 문제리스트를 업데이트하였습니다.' || echo
          git push
